# Generated by Django 5.1.4 on 2025-01-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="cancellation_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
