# Generated by Django 5.1.4 on 2025-01-12 12:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0002_alter_booking_cancellation_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Özellikler'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Rezervasyonlar'},
        ),
        migrations.AlterModelOptions(
            name='cancellationpolicy',
            options={'verbose_name_plural': 'İptal Politikaları'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name_plural': 'Promo Kodları'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'İncelemeler'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'Odalar'},
        ),
        migrations.AlterModelOptions(
            name='seasonalprice',
            options={'verbose_name_plural': 'Sezon Fiyatı'},
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(help_text='Örnek, Wi-Fi', max_length=50, unique=True, verbose_name='Özellik Adı'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancellation_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İptal Son Tarihi'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(verbose_name='Giriş Tarihi'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(verbose_name='Çıkış Tarihi'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_booking.promocode', verbose_name='Promosyon Kodu'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İade Tutarı'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.room', verbose_name='Oda'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='cancellationpolicy',
            name='hours_before',
            field=models.IntegerField(verbose_name='Önceki Saatler'),
        ),
        migrations.AlterField(
            model_name='cancellationpolicy',
            name='refund_percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İade Yüzdesi'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Promosyon Kodu'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='current_uses',
            field=models.IntegerField(default=0, verbose_name='Mevcut Kullanım'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İndirim Yüzdesi'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.IntegerField(verbose_name='Maksimum Kullanım'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Geçerli Başlangıç'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_until',
            field=models.DateTimeField(verbose_name='Geçerli Bitiş'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Yorum'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puan'),
        ),
        migrations.AlterField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.room', verbose_name='Oda'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(to='hotel_booking.amenity', verbose_name='Özellikler'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2, verbose_name='Kapasite'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(verbose_name='Kat'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_balcony',
            field=models.BooleanField(default=False, verbose_name='Balkon'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_sea_view',
            field=models.BooleanField(default=False, verbose_name='Deniz Manzaralı'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Oda Adı'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('family', 'Family')], max_length=20, verbose_name='Oda Tipi'),
        ),
        migrations.AlterField(
            model_name='seasonalprice',
            name='end_date',
            field=models.DateField(verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='seasonalprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='seasonalprice',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.room', verbose_name='Oda'),
        ),
        migrations.AlterField(
            model_name='seasonalprice',
            name='start_date',
            field=models.DateField(verbose_name='Başlangıç Tarihi'),
        ),
    ]
