# Generated by Django 5.1.4 on 2025-01-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_booking", "0003_alter_amenity_options_alter_booking_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="İsim")),
                ("email", models.EmailField(max_length=254, verbose_name="E-posta")),
                ("subject", models.CharField(max_length=200, verbose_name="Konu")),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Gönderilme Tarihi"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Okundu")),
            ],
            options={
                "verbose_name": "İletişim Mesajı",
                "verbose_name_plural": "İletişim Mesajları",
                "ordering": ["-created_at"],
            },
        ),
    ]
