# Generated by Django 5.1.4 on 2025-01-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_booking", "0004_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Beklemede"),
                    ("confirmed", "Onaylandı"),
                    ("cancelled", "İptal Edildi"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("single", "Tek Kişilik"),
                    ("double", "Çift Kişilik"),
                    ("suite", "Suit"),
                    ("family", "Aile"),
                ],
                max_length=20,
                verbose_name="Oda Tipi",
            ),
        ),
    ]
