# Generated by Django 5.1.4 on 2025-01-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_booking", "0005_alter_booking_status_alter_room_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="ai_analysis",
            field=models.TextField(
                blank=True, null=True, verbose_name="AI Yorum Analizi"
            ),
        ),
    ]
